language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t felixricks/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iuriimudrak/react-test npm test

after_success:
  - docker build -t felixricks/multi-client ./client
  - docker build -t felixricks/multi-nginx ./nginx
  - docker build -t felixricks/multi-server ./server
  - docker build -t felixricks/multi-worker ./worker
  # Log into the Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push it to Docker Hub
  - docker push felixricks/multi-client
  - docker push felixricks/multi-nginx
  - docker push felixricks/multi-server
  - docker push felixricks/multi-worker
